### PR TITLE
Fix Thunderbird sync full address book

### PR DESCRIPTION
**Pull request by chris001**
From Egoitz Aurrekoetxea.  "Have you previously uploaded from another Thunderbird Sogo connector all your contacts?. I have suffered some issues with it and Davical. I wrote a little patch that made it work properly... "

### CODE REVIEW

**Comment by extrafu** [comment]
Can we have a bit more context about the issue + fix?

**Comment by chris001** [comment]
Sure. Sorry.  Here's the thread from the sogo mailing list with the discussion of the problem cause and the fix, which the user "Egoitz Aurrekoetxea" has tested it enough to attach and share a repacked fixed version of the xpi connector!
http://comments.gmane.org/gmane.comp.groupware.sogo.user/23384

**Comment by chris001** [comment]
It has to do with the timeout while syncing the full address book, something that might take a minute on congested internet connection to the server.  So you put the connection in synchronous mode (foreground processing) instead of async (background processing).

**Comment by Victor-D** [comment]
Hi

I am very interested with this feature.

I have several Zimbra accounts with more than 1500 contacts and the full resync last more than 10 seconds and freeze Thunderbird. In addition, the "stop script popup" often shows during this operation resulting in random behaviors on low hardware computers or when -console is enabled.

Regards

Victor

**Comment by chris001** [comment]
The idea is to force "synchronous" mode when there is a write operation on the contact (either PUT or DELETE Webdav command).  The call only returns after the network write is complete.  This forces the thunderbird user interface to wait until the write operation is completed before letting the user do anything that could possibly interrupt the write operation of the contact and cause it to fail.

**Pull request merged**
